name: Request Render between 14 minutes

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  render-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get Products
        env:
          API_URL: ${{ secrets.API_URL }} # Utiliza o secret aqui
        run: curl $API_URL
